resolver: lts-12.17

packages:
- .

extra-deps:
- nanovg-0.6.0.0
- git: https://github.com/bsl/bindings-GLFW.git
  commit: 09a004908872b359feaf34241d74ab9fa31f21bd

flags:
  nanovg-simple:
    library-only: false
